name: "clang-format checker"
description: "use clang-format version 9 to determine if C++ code is properly formatted."

branding:
  icon: "thumbs-up"
  color: "green"

runs:
  using: "docker"
  image: "Dockerfile"